language: go

go:
  - 1.8.x
  - master

script:
  - make test

after_script:
  - go build .

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
      - goby-lang:Ler5Uge2Vlx3O8Yt2OFcKg5W
    on_success: change
    on_failure: always
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/149378fb1b44bbaf21f0
    on_success: change
    on_failure: always
    on_start: never
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
