language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

script:
  - ./test.sh

after_script:
  - go build .

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never