language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

script:
  - go test ./... -v -cover -race

after_script:
  - go build .

notifications:
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never